### ISSUE TITLE
ALB controller always restarting due to Controller health check failed 

### ISSUE THREAD

**Issue by eserden** [kubernetes-sigs/aws-alb-ingress-controller#739]
Hello all. 

I have faced with issue once installed release version 1.0.0.
```-------------------------------------------------------------------------------
AWS ALB Ingress controller
  Release:    v1.0.0
  Build:      git-8115b25
  Repository: https://github.com/kubernetes-sigs/aws-alb-ingress-controller
-------------------------------------------------------------------------------

W1119 16:24:00.773769       1 config.go:46] Environment variable configuration is deprecated, switch to the --aws-region flag.
W1119 16:24:00.774023       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1119 16:24:00.828036       1 :0] kubebuilder/controller "level"=0 "msg"="Starting EventSource"  "Controller"="alb-ingress-controller" "Source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{},"status":{"loadBalancer":{}}}}
I1119 16:24:00.828264       1 :0] kubebuilder/controller "level"=0 "msg"="Starting EventSource"  "Controller"="alb-ingress-controller" "Source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{},"status":{"loadBalancer":{}}}}
I1119 16:24:00.828405       1 :0] kubebuilder/controller "level"=0 "msg"="Starting EventSource"  "Controller"="alb-ingress-controller" "Source"={"Type":{"metadata":{"creationTimestamp":null}}}
I1119 16:24:00.828627       1 :0] kubebuilder/controller "level"=0 "msg"="Starting EventSource"  "Controller"="alb-ingress-controller" "Source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{},"status":{"daemonEndpoints":{"kubeletEndpoint":{"Port":0}},"nodeInfo":{"machineID":"","systemUUID":"","bootID":"","kernelVersion":"","osImage":"","containerRuntimeVersion":"","kubeletVersion":"","kubeProxyVersion":"","operatingSystem":"","architecture":""}}}}
I1119 16:24:00.828800       1 leaderelection.go:185] attempting to acquire leader lease  nginx/ingress-controller-leader-alb...
I1119 16:24:19.049773       1 leaderelection.go:194] successfully acquired lease nginx/ingress-controller-leader-alb
I1119 16:24:19.150170       1 :0] kubebuilder/controller "level"=0 "msg"="Starting Controller"  "Controller"="alb-ingress-controller"
I1119 16:24:19.250323       1 :0] kubebuilder/controller "level"=0 "msg"="Starting workers"  "Controller"="alb-ingress-controller" "WorkerCount"=1
E1119 16:24:39.439349       1 healthcheck.go:38] Controller health check failed: [ec2.DescribeTagsWithContext]: InvalidParameterValue: Value ( 1 ) for parameter maxResults is invalid. Expecting a value greater than 5.
	status code: 400, request id: 0e1beb6e-f482-4e52-9364-a05257b1d611
E1119 16:24:49.447230       1 healthcheck.go:38] Controller health check failed: [ec2.DescribeTagsWithContext]: InvalidParameterValue: Value ( 1 ) for parameter maxResults is invalid. Expecting a value greater than 5.```

**Comment by dshmatov** [comment]
@eserden I have the same issue with v1.0.0 I guess [this](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/48f365724488bf8b4f4deddd60f7ccda06a778f5/internal/aws/ec2.go#L248) should be fixed

**Comment by M00nF1sh** [comment]
will fix this asap, it's an degrade from 1.0-beta.7 by https://github.com/kubernetes-sigs/aws-alb-ingress-controller/commit/f7382830d1e212e5e7f3e9f00e59a6ea170adec0.
I didn't capture this without configure the health probe

**Comment by M00nF1sh** [comment]
A temp mitigation can be remove the liveness/readiness probe from controller yaml.
I'll send an PR to fix this shortly and re-release v1.0.0 to contain it

**Comment by M00nF1sh** [comment]
Hi, I just re-tagged the v1.0.0 tag and have rebuilt the v1.0.0 image by travis.
Sorry for the inconvenience caused. I'll add health checks into my integration test suit.

**Comment by coderise-ahsan** [comment]
@M00nF1sh when I am turing on the healthcheck, I am still facing the same issue in v1.0.1

```
0109 14:38:45.299334       1 healthcheck.go:38] Controller health check failed: [ec2.DescribeTagsWithContext]: UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: 1418aa4d-6afb-4a7e-b85f-02231af7491b
E0109 14:39:45.241338       1 healthcheck.go:38] Controller health check failed: [ec2.DescribeTagsWithContext]: UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: dff87b0c-e789-463d-a611-94247c3d08d4
E0109 14:40:45.237746       1 healthcheck.go:38] Controller health check failed: [ec2.DescribeTagsWithContext]: UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: 96bb2883-a78d-4ff7-a700-d308b6258029
```
Can you please help fix it ?
